spin_manifest_version = 2

[application]
name = "ms"
version = "0.1.0"
authors = ["Alexander Svobodov <31383841+sidecuter@users.noreply.github.com>"]
description = "Helper for solving matstat tasks"

[[trigger.http]]
route = "/..."
component = "ms"

[component.ms]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "dist", destination = "/" }]

[component.ms.build]
command = "trunk build --release"
